---
- name: Restart Nginx
  service: name=nginx state=restarted
  become: yes


- name: ufw-allow-web port 80
  ufw: rule=allow port=80 proto=tcp
  listen: ufw-allow-web
  become: yes

- name: ufw-allow-web port 443
  ufw: rule=allow port=443 proto=tcp
  listen: ufw-allow-web
  become: yes